name: Daily Scheduled Action

on:
  schedule:
    # Setiap hari jam 07:00 UTC
    - cron: '0 7 * * *'

jobs:
  daily-job:
    runs-on: ubuntu-latest
    steps:
      - name: Show daily message
        run: echo "Hello, world! This action runs every day!"
